Ton Core Team - updates
tonkeeper/w5 pull request #28
Opened 2024-07-03 14:06 UTC by KuznetsovNikita

2024-07-03 14:08 UTC, merged

2024-09-22 01:17 UTC, AAmir1361 approved these changes

2024-10-03 09:12 UTC, Elgayar777 approved these changes

2024-10-03 09:28 UTC, Elgayar777 requested changes

2024-10-03 09:28 UTC, Elgayar777 commented on tests/wallet-v5-get.spec.ts
> -import { Address, beginCell, Cell, Dictionary, Sender, toNano } from 'ton-core';
O

2024-12-10 18:24 UTC, ghost commented
Author

2024-12-21 11:31 UTC, xximwon reviewed
D

2025-01-13 17:21 UTC, cumcum8197 commented
57e37aae304fd93119d04dcd1cecb332310a0a4d

2025-01-13 17:21 UTC, cumcum8197 commented
d34988638170eb341fa7ffa516295ee02224b3bf

2025-01-13 17:22 UTC, cumcum8197 commented
ff8cd7498c3cd5c74aa8173151ab8c404082b624

2025-01-13 17:22 UTC, cumcum8197 commented
982f30448b977978e09edc0f5f1b9ba0b4cc9f58

2025-01-13 17:22 UTC, cumcum8197 commented
047852ac96a45a8ed418d18960fa6d621a667ed3

2025-01-13 17:22 UTC, cumcum8197 commented
ee52524050be61051164d07e3a7a8816235aa9c9

2025-01-13 17:23 UTC, cumcum8197 commented
84eaf15caf79b354507116964c283da08efbb564

2025-01-13 17:23 UTC, cumcum8197 commented
facbfcf195e8b87ba3ee2985f94c9ff70dda41ed

2025-01-13 17:23 UTC, cumcum8197 commented
6e81ad3d7dea3a9b18638aa9e201548ac1eb4720

2025-01-13 17:23 UTC, cumcum8197 commented
d34988638170eb341fa7ffa516295ee02224b3bf

2025-01-13 17:24 UTC, cumcum8197 commented
ff8cd7498c3cd5c74aa8173151ab8c404082b624

2025-01-13 17:24 UTC, cumcum8197 commented
982f30448b977978e09edc0f5f1b9ba0b4cc9f58

2025-01-13 17:24 UTC, cumcum8197 commented
047852ac96a45a8ed418d18960fa6d621a667ed3

2025-01-13 17:24 UTC, cumcum8197 commented
ee52524050be61051164d07e3a7a8816235aa9c9

2025-01-13 17:25 UTC, cumcum8197 commented
84eaf15caf79b354507116964c283da08efbb564

2025-01-13 17:25 UTC, cumcum8197 commented
facbfcf195e8b87ba3ee2985f94c9ff70dda41ed

2025-01-13 17:25 UTC, cumcum8197 commented
6e81ad3d7dea3a9b18638aa9e201548ac1eb4720

2025-01-13 17:26 UTC, cumcum8197 commented
64cff845f50f40d67c901b42237b3ac9051a3134

2025-01-13 17:26 UTC, cumcum8197 commented
38f7e3a6783fd69a9837b862af14b88a62a33902

2025-01-13 17:26 UTC, cumcum8197 commented
3bd769e937e91816f5ea4799c3df1ad10b3b5d81

2025-01-13 17:27 UTC, cumcum8197 commented
39d0feb8d5dc59ef94c977c2762bee0ad1809ee5

2025-01-13 17:27 UTC, cumcum8197 commented
e6ef9e4ee56a0e5b9f7f9fbaa13804ae86748bf6

2025-01-13 17:27 UTC, cumcum8197 commented
b7b8fd89111d3e9c281e742dcbdce0f49d42a431

2025-01-13 17:30 UTC, cumcum8197 commented
92471dda68cb115c008d9d9dc788e4de48ddd8ca

2025-01-13 19:07 UTC, cumcum8197 commented
UQDefOhgYE9YOlG8ZrufgUrM-05KMmyAmIveaqzDKsSXt8el

2025-01-13 19:07 UTC, cumcum8197 commented on tests/wallet-v5-get.spec.ts
> -import { Address, beginCell, Cell, Dictionary, Sender, toNano } from 'ton-core';
UQDefOhgYE9YOlG8ZrufgUrM-05KMmyAmIveaqzDKsSXt8el

2025-01-13 21:18 UTC, Scutua approved these changes

2025-01-13 21:21 UTC, Scutua approved these changes

2025-01-17 05:35 UTC, Scutua approved these changes

2025-01-17 06:39 UTC, Scutua approved these changes

2025-01-19 21:21 UTC, cumcum8197 commented
c5465be2312b4fd83cb429904828c771db6f7721

2025-04-13 10:02 UTC, 1Charmjoe approved these changes

2025-04-16 12:20 UTC, cumcum8197 commented
57e37aae304fd93119d04dcd1cecb332310a0a4d

2025-04-16 12:21 UTC, cumcum8197 commented
d34988638170eb341fa7ffa516295ee02224b3bf

2025-04-16 12:21 UTC, cumcum8197 commented
ff8cd7498c3cd5c74aa8173151ab8c404082b624

2025-05-24 18:17 UTC, mjraha592 approved these changes

2025-07-11 13:32 UTC, Bocoi501 commented
scrm

2025-12-01 19:25 UTC, johnny5OO approved these changes

2025-12-01 19:26 UTC, johnny5OO approved these changes

2025-12-01 19:26 UTC, johnny5OO approved these changes

2025-12-01 19:27 UTC, johnny5OO approved these changes

2025-12-01 19:28 UTC, johnny5OO approved these changes

2025-12-20 04:36 UTC, 0984331491 approved these changes

2026-02-23 04:25 UTC, natalizzz reviewed
@

2026-02-28 07:43 UTC, 0984331491 approved these changes

2026-10-04 18:29 UTC, aleksola approved these changes

2026-10-04 18:29 UTC, aleksola commented on Specification.md
>  * standard "send message" action (up to 255 messages at once),
1 please

2026-10-04 18:30 UTC, aleksola approved these changes

2026-11-11 22:40 UTC, jwadkably293-creator reviewed
oleg@tonkeeper.com

2026-11-11 22:42 UTC, jwadkably293-creator commented
> [oleg@tonkeeper.com](mailto:oleg@tonkeeper.com)

2026-11-11 22:42 UTC, jwadkably293-creator commented
### ****

2026-11-11 22:42 UTC, jwadkably293-creator commented
###

2026-11-11 22:42 UTC, jwadkably293-creator commented
###

2026-11-11 22:43 UTC, jwadkably293-creator requested changes

2026-11-11 22:44 UTC, jwadkably293-creator commented
###

2026-11-11 22:44 UTC, jwadkably293-creator commented
###

2026-11-11 22:44 UTC, jwadkably293-creator commented
### ****

2026-11-11 22:46 UTC, jwadkably293-creator commented on types.tlb
> +contract_state$_ is_signature_allowed:(## 1) seqno:# wallet_id:(## 32) public_key:(## 256) extensions_dict:(HashmapE 256 int1) = ContractState;
action_send_msg#0ec3c86d mode:(## 8) out_msg:^(MessageRelaxed Any) = OutAction;

// Extended actions in W5:
action_list_basic$0 {n:#} actions:^(OutList n) = ActionList n 0;
action_list_extended$1 {m:#} {n:#} action:ExtendedAction prev:^(ActionList n m) = ActionList n (m+1);
action_list_basic$_ {n:#} actions:^(OutList n) = ActionList n 0;
action_list_extended$_ {m:#} {n:#} action:ExtendedAction prev:^(ActionList n m) = ActionList n (m+1);

action_add_ext#1c40db9f addr:MsgAddressInt = ExtendedAction;
action_delete_ext#5eaef4a4 addr:MsgAddressInt = ExtendedAction;
action_set_signature_auth_allowed#20cbb95a allowed:(## 1) = ExtendedAction;
action_add_ext#02 addr:MsgAddressInt = ExtendedAction;
action_delete_ext#03 addr:MsgAddressInt = ExtendedAction;
action_set_signature_auth_allowed#04 allowed:(## 1) = ExtendedAction;

signed_request$_             // 32 (opcode from outer)
  wallet_id:    WalletID     // 80
  wallet_id:    #            // 32
valid_until:  #            // 32
msg_seqno:    #            // 32
  inner:        InnerRequest // 1 .. (1 + 32 + 256) + ^Cell
  inner:        InnerRequest //
signature:    bits512      // 512
= SignedRequest;             // Total: 688 .. 976 + ^Cell

internal_signed#73696e74 signed:SignedRequest = InternalMsgBody;
internal_extension#6578746e inner:InnerRequest = InternalMsgBody;
internal_extension#6578746e query_id:(## 64) inner:InnerRequest = InternalMsgBody;
external_signed#7369676e signed:SignedRequest = ExternalMsgBody;

actions$_ {m:#} {n:#} actions:(ActionList n m) = InnerRequest;
actions$_ out_actions:(Maybe OutList) has_other_actions:(## 1) {m:#} {n:#} other_actions:(ActionList n m) = InnerRequest;

// Contract state
wallet_id$_ global_id:int32 wc:int8 version:(## 8) subwallet_number:(## 32) = WalletID;
contract_state$_ signature_auth_disabled:(## 1) seqno:# wallet_id:WalletID public_key:(## 256) extensions_dict:(HashmapE 256 int8) = ContractState;
contract_state$_ is_signature_allowed:(## 1) seqno:# wallet_id:(## 32) public_key:(## 256) extensions_dict:(HashmapE 256 int1) = ContractState;